FROM rust:latest as builder
WORKDIR /usr/src/application

COPY Cargo.lock Cargo.toml ./
COPY src/*.rs ./src/

RUN cargo build --release --bins

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libgcc-10-dev && rm -rf /var/lib/apt/lists/
COPY --from=builder /usr/src/application/target/release/producer /usr/local/bin/producer

CMD ["/usr/local/bin/producer"]
