FROM rust:latest as builder
WORKDIR /usr/src/application

COPY . .

RUN cargo build --release --bins

FROM scratch
COPY --from=builder /usr/src/application/target/release/consumer /usr/local/bin/consumer

CMD "/usr/local/bin/consumer"
